logging:
  path: ./logs

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:5000/eureka/}

server:
  port: 9999
  contextPath: /uaa
security:
  user:
    name: jalgoarena_user
    password: password
  oauth2:
    client:
      clientId: jalgoarena
      clientSecret: jalgoarenasecret
      authorizedGrantTypes: authorization_code,refresh_token,password
      scope: openid
---
spring:
  profiles: heroku
eureka:
  instance:
    hostname: ${APP_NAME}.herokuapp.com
    nonSecurePort: 80
security:
  oauth2:
    client:
      clientSecret: ${CLIENT_SECRET}
logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO
